(() => {
'use strict';
const $=id=>document.getElementById(id),book=window.DE_BOOK,qs=book?.questions||[],byId=new Map(qs.map(q=>[q.id,q]));let current,unit=4;
if(!qs.length){$('question-title').textContent='Solutions could not load. Please reload.';return;}
function browse(){const term=$('question-search').value.toLowerCase().trim();const matches=qs.filter(q=>q.unit===unit&&(!term||String(q.id).includes(term)||q.question.toLowerCase().includes(term)));$('question-select').replaceChildren(...matches.map(q=>{const o=document.createElement('option');o.value=q.id;o.textContent=`Q${q.id} · ${q.question.slice(0,95)}`;return o;}));if(current&&matches.some(q=>q.id===current.id))$('question-select').value=current.id;$('jump-message').textContent=`${matches.length} questions in this chapter${term?' match your search':''}.`;document.querySelectorAll('[data-unit]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.unit)===unit)));}
function render(id,write=true){const q=byId.get(Number(id));if(!q){$('jump-message').textContent='Choose a whole question number from 334 to 537.';return false;}current=q;if(unit!==q.unit){unit=q.unit;$('question-search').value='';}browse();$('question-number').value=q.id;$('question-title').textContent=`Q${q.id} · Chapter ${q.unit}`;$('question-text').textContent=q.question;document.querySelector('.original').open=/figure|map represent/i.test(q.question);$('question-source').setAttribute('viewBox',q.crop.join(' '));$('question-source').setAttribute('aria-label',`Original PDF row for Q${q.id}`);$('source-image').setAttribute('href',q.image);$('source-image').setAttribute('width',q.pageWidth);$('source-image').setAttribute('height',q.pageHeight);$('source-link').href=`practice-book.pdf#page=${q.page}`;$('question-note').textContent=q.note||'';$('solution-title').textContent=`Q${q.id} — Solution`;$('steps').innerHTML=q.solution;$('answer').textContent=q.answer;$('solution').hidden=true;$('show-solution').textContent='Show solution';$('show-solution').setAttribute('aria-expanded','false');$('previous-question').disabled=q.id===334;$('next-question').disabled=q.id===537;window.StudyTools?.mount($('de-study-tools'),'de:'+q.id);if(write)history.replaceState(null,'','#q'+q.id);return true;}
function reveal(){ $('solution').hidden=false;$('show-solution').textContent='Hide solution';$('show-solution').setAttribute('aria-expanded','true'); }
function access(action){const id=current.id;if(window.QuestionAccess)window.QuestionAccess.require(()=>{if(current.id===id)action();});else window.StudyTools?.notice('Login could not load. Reload this page to see the solution.');}
$('show-solution').onclick=()=>{if(!$('solution').hidden){$('solution').hidden=true;$('show-solution').textContent='Show solution';$('show-solution').setAttribute('aria-expanded','false');}else access(reveal);};
$('print-solution').onclick=()=>access(()=>{reveal();window.print();});$('jump-form').onsubmit=e=>{e.preventDefault();$('question-search').value='';render($('question-number').value);};$('question-search').oninput=browse;$('question-select').onchange=()=>render($('question-select').value);$('previous-question').onclick=()=>render(current.id-1);$('next-question').onclick=()=>render(current.id+1);$('random-question').onclick=()=>{const list=qs.filter(q=>q.unit===unit);render(list[Math.floor(Math.random()*list.length)].id);};document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>render(Number(b.dataset.unit)===4?334:464));window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#q(\d+)$/);if(m)render(m[1],false);});const m=location.hash.match(/^#q(\d+)$/);render(m&&byId.has(Number(m[1]))?m[1]:334,false);window.QuestionAccess?.resumeSolution(reveal);
})();
