(()=>{'use strict';
const C=window.INTERNSHIP_COURSE,$=id=>document.getElementById(id),KEY='ljiet_python_internship_v1';
const validIds=new Set(C.lessons.map(l=>l.id));let state={version:1,lessons:{},projects:{},current:C.lessons[0].id},lesson,worker,busy=null,timer,serial=0,storageOK=true;
function cleanState(raw){
 const s={version:1,lessons:{},projects:{},current:C.lessons[0].id};
 if(!raw||raw.version!==1||typeof raw.lessons!=='object')throw Error('Unsupported backup. Use an exported course backup.');
 for(const l of C.lessons){const r=raw.lessons[l.id];if(!r||typeof r!=='object')continue;const code=typeof r.code==='string'?r.code.slice(0,50000):l.starter;
 s.lessons[l.id]={code,guidedCode:typeof r.guidedCode==='string'?r.guidedCode.slice(0,50000):undefined,reflection:typeof r.reflection==='string'?r.reflection.slice(0,5000):'',hints:Math.max(0,Math.min(3,Number(r.hints)||0)),reference:!!r.reference,prediction:Number.isInteger(r.prediction)?r.prediction:null,passed:!!r.passed&&r.checkedCode===code,checkedCode:typeof r.checkedCode==='string'?r.checkedCode.slice(0,50000):'',assisted:!!r.assisted};}
 for(const w of C.weeks){const p=raw.projects?.[w.number];if(!p||typeof p!=='object')continue;s.projects[w.number]={checks:w.requirements.map((_,i)=>!!p.checks?.[i]),link:safeURL(p.link),reflection:typeof p.reflection==='string'?p.reflection.slice(0,5000):'',reviewed:!!p.reviewed&&w.requirements.every((_,i)=>p.checks?.[i])&&typeof p.reflection==='string'&&p.reflection.trim().length>=30};}
 if(validIds.has(raw.current))s.current=raw.current;return s;
}
function safeURL(value){if(!value)return '';try{const u=new URL(value);return u.protocol==='https:'?u.href.slice(0,2000):''}catch{return ''}}
try{const saved=localStorage.getItem(KEY);if(saved)state=cleanState(JSON.parse(saved));}catch{storageOK=false;}
function record(l=lesson){return state.lessons[l.id]||(state.lessons[l.id]={code:l.starter,reflection:'',hints:0,reference:false,prediction:null,passed:false,checkedCode:'',assisted:false});}
function project(){return state.projects[lesson.week]||(state.projects[lesson.week]={checks:[false,false,false],link:'',reflection:'',reviewed:false});}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;$('save-status').textContent='Saved on this device. Export a backup before clearing browser data.';}catch{storageOK=false;$('save-status').textContent='Browser storage unavailable. Your work is in this session only; export a backup now.';}}
function counters(){const rows=Object.values(state.lessons);$('independent').textContent=rows.filter(r=>r.passed&&!r.assisted).length;$('assisted').textContent=rows.filter(r=>r.passed&&r.assisted).length;$('reviewed').textContent=Object.values(state.projects).filter(p=>p.reviewed).length;}
function showNav(){const nav=$('week-list');nav.replaceChildren();['Python foundations','Reliable Python programs','Web development','Data, AI and portfolio'].forEach((name,m)=>{const d=document.createElement('details');d.open=Math.floor((lesson.week-1)/4)===m;const summary=document.createElement('summary');summary.textContent=`Month ${m+1} · ${name}`;d.append(summary);C.weeks.slice(m*4,m*4+4).forEach(w=>{const b=document.createElement('button');b.type='button';b.className=w.number===lesson.week?'active':'';b.textContent=`${String(w.number).padStart(2,'0')} · ${w.title}`;const status=document.createElement('small');const core=C.lessons.filter(l=>l.week===w.number&&l.level!=='stretch');const count=core.filter(l=>state.lessons[l.id]?.passed).length;status.textContent=`${count}/${core.length} core checks passed`;b.append(status);b.onclick=()=>openLesson(C.lessons.find(l=>l.week===w.number).id);d.append(b)});nav.append(d)});}
function checkpoint(){const w=C.weeks[lesson.week-1];$('checkpoint').hidden=!w.checkpoint;if(!w.checkpoint)return;const tasks=[
 'Rebuild a budget planner without the reference. Add an extra expense category, handle invalid input and explain two boundary tests.',
 'From an empty folder, build a tested notes CLI with JSON storage. Write setup instructions and ask someone else to run it.',
 'Run your task API and dashboard together. Demonstrate a successful request, validation failure and unavailable server. Test on a narrow screen.',
 'Show the AI support desk, held-out evaluation and no-match retrieval. Add a feature with a test and explain the model’s limits without reading the README.'
];$('checkpoint-task').textContent=tasks[Math.floor((lesson.week-1)/4)];const first=w.number-3;let independent=0;for(const l of C.lessons.filter(l=>l.week>=first&&l.week<=w.number&&l.level!=='stretch')){const r=state.lessons[l.id];if(r?.passed&&!r.assisted)independent++;}$('checkpoint-status').textContent=`${independent}/${C.lessons.filter(l=>l.week>=first&&l.week<=w.number&&l.level!=='stretch').length} lessons checked without hints this month. This is a suggested independent challenge; completion is not automatically verified.`;}
function openLesson(id){
 const found=C.lessons.find(l=>l.id===id);if(!found)return;
 if(busy)stop('Run stopped because you changed lessons.');lesson=found;state.current=id;const r=record(),w=C.weeks[lesson.week-1];
 $('week-number').textContent=`WEEK ${String(lesson.week).padStart(2,'0')} / 16`;$('week-title').textContent=w.title;$('week-outcome').textContent=w.outcome;
 $('lesson-number').textContent=`LESSON ${C.lessons.filter(l=>l.week===lesson.week).indexOf(lesson)+1} / ${C.lessons.filter(l=>l.week===lesson.week).length}`;$('lesson-title').textContent=lesson.title;$('goal').textContent=lesson.goal;$('teach').textContent=lesson.teach;$('example').textContent=lesson.example;$('change').textContent=lesson.change;
 $('editor').value=r.code;$('reflection').value=r.reflection;$('reflection-label').textContent=lesson.reflection;
 $('runtime-note').textContent=lesson.language==='html'?'Write a complete HTML page, including CSS or JavaScript. Preview runs in an isolated frame. Structure checks are limited; manually test clicks and keyboard behaviour.':'Follow the task above. Keep the requested names so checks can find your answer. Use print to inspect values. Files inside this quick runner are temporary.';
 $('output').textContent='';$('results').replaceChildren();$('preview').hidden=true;$('preview').srcdoc='';$('run-status').textContent=r.passed?(r.assisted?'Checks passed with help. Try a fresh variation independently.':'Checks passed without opening hints or the reference.'):'Write your code, then check it.';
 $('reference').textContent=lesson.reference;$('reference').hidden=true;$('reference-toggle').setAttribute('aria-expanded','false');$('hint-text').textContent=r.hints?lesson.hints[r.hints-1]:'';$('hint').textContent=r.hints>=3?'All 3 hints opened':`Need a hint? (${r.hints}/3)`;
 $('prediction-code').textContent=lesson.prediction.code;$('prediction-feedback').textContent='';const options=$('prediction-options');options.replaceChildren();lesson.prediction.options.forEach((text,i)=>{const b=document.createElement('button');b.textContent=text;b.type='button';b.setAttribute('aria-pressed',String(r.prediction===i));b.onclick=()=>{r.prediction=i;save();$('prediction-feedback').textContent=(i===lesson.prediction.correct?'Correct. ':'Try tracing it again. ')+lesson.prediction.explanation;Array.from(options.children).forEach((el,j)=>el.setAttribute('aria-pressed',String(j===i)))};options.append(b)});
 $('resource').href=lesson.resources[0].url;$('resource').textContent=lesson.resources[0].title+' ↗';const tabs=$('lesson-tabs'),stretch=$('stretch-tabs'),select=$('lesson-select');tabs.replaceChildren();stretch.replaceChildren();select.replaceChildren();const weekly=C.lessons.filter(l=>l.week===lesson.week);weekly.forEach((l,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${l.level==='guided'?'Learn':l.level==='stretch'?'Stretch':'Practise'} · ${l.title}`;b.setAttribute('aria-pressed',String(l.id===id));b.onclick=()=>openLesson(l.id);(l.level==='stretch'?stretch:tabs).append(b);if(l.level!=='stretch'||l.id===id){const option=document.createElement('option');option.value=l.id;option.textContent=b.textContent;select.append(option);}});select.value=id;$('stretch-group').hidden=!stretch.children.length;$('stretch-group').open=lesson.level==='stretch';window.CourseLearning?.render(lesson,r);
 $('project-title').textContent=w.project;$('project-download').href=w.download;const p=project();$('project-link').value=p.link;$('project-reflection').value=p.reflection;$('project-status').textContent=p.reviewed?'Self-review saved. Ask a teacher or friend for an independent review.':'';const list=$('project-checklist');list.replaceChildren();w.requirements.forEach((text,i)=>{const label=document.createElement('label');label.className='check-row';const box=document.createElement('input');box.type='checkbox';box.checked=p.checks[i];box.onchange=()=>{p.checks[i]=box.checked;p.reviewed=false;$('project-status').textContent='Review changed; save it again when ready.';save();counters()};label.append(box,document.createTextNode(text));list.append(label)});
 showNav();counters();checkpoint();save();$('weeks').classList.remove('open');$('menu').setAttribute('aria-expanded','false');
 if(location.hash!==`#${id}`)history.replaceState(null,'',`#${id}`);
}
function buttons(active){$('guided-run').disabled=active;$('run').disabled=active;$('check').disabled=active;$('stop').disabled=!active;}
function stop(message='Stopped. You can edit and run again.'){if(worker){worker.terminate();worker=null;}clearTimeout(timer);busy=null;buttons(false);$('run-status').textContent=message;}
function checksHTML(code){
 const d=new DOMParser().parseFromString(code,'text/html'),css=Array.from(d.querySelectorAll('style')).map(s=>s.textContent).join('\n'),script=Array.from(d.querySelectorAll('script')).map(s=>s.textContent).join('\n');
 return lesson.tests.map(t=>{let pass=false;try{if(t.kind==='text')pass=!!d.querySelector(t.selector)?.textContent.trim();if(t.kind==='count')pass=d.querySelectorAll(t.selector).length>=t.min;if(t.kind==='zero')pass=d.querySelector(t.selector)?.textContent.trim()==='0';if(t.kind==='emailLabel'){const input=d.querySelector('input[type=email][id]');pass=!!input&&Array.from(d.querySelectorAll('label[for]')).some(l=>l.htmlFor===input.id&&l.textContent.trim())}if(t.kind==='cssGrid')pass=/display\s*:\s*grid/.test(css)&&/repeat\s*\(\s*auto-(?:fit|fill)\s*,\s*minmax\s*\(/.test(css);if(t.kind==='focus')pass=/:focus-visible\s*\{[^}]*outline\s*:/.test(css);if(t.kind==='event')pass=/addEventListener\s*\(\s*['"]click['"]/.test(script)&&/textContent/.test(script)}catch{}return {label:t.label,pass,error:pass?'':'Required structure is missing. Review the task and try again.'}});
}
function finish(results,output,job,error){if(!busy||job.id!==busy.id||job.lessonId!==lesson.id)return;clearTimeout(timer);busy=null;buttons(false);if(job.guided){$('guided-output').textContent=(output||'')+(error?'\n'+error:'');if(error)window.CourseLearning?.errorHelp(error);$('run-status').textContent='Example run finished. Now try the independent task below.';return;}$('output').textContent=output||'';const list=$('results');list.replaceChildren();for(const r of results||[]){const li=document.createElement('li');li.className=r.pass?'pass':'fail';li.textContent=(r.pass?'✓ ':'✗ ')+r.label+(r.error?' — '+r.error:'');list.append(li)}
 if(error){window.CourseLearning?.errorHelp(error);$('run-status').textContent='Python could not finish. Read the error and try again.';$('output').textContent=(output||'')+'\n'+error;return;}
 if(job.check){const r=record();const passed=results.length===lesson.tests.length&&results.every(t=>t.pass);if(r.code===job.code){r.passed=passed;r.checkedCode=passed?job.code:'';r.assisted=!!(r.hints||r.reference);save();counters();showNav();checkpoint();$('run-status').textContent=passed?`All ${results.length} checks passed${r.assisted?' with help':''}. Explain why your code works, then try a variation.`:'Some checks failed. Use the case labels to debug.';}else $('run-status').textContent='Code changed during the run. Check the current version again.';
 }else $('run-status').textContent='Run complete. Use Check my code to run the exercise cases.';
}
function run(check,guided=false){if(busy)return;const code=$(guided?'guided-editor':'editor').value;if(guided)record().guidedCode=code;else record().code=code;save();const job={id:++serial,lessonId:lesson.id,code,check,guided};$('error-help').hidden=true;busy=job;buttons(true);$('results').replaceChildren();$('output').textContent='';$('run-status').textContent='Running your code…';
 if(lesson.language==='html'){$('preview').hidden=false;$('preview').srcdoc=code;finish(check?checksHTML(code):[],'Preview loaded. Try the interaction and keyboard navigation.',job);return;}
 $('preview').hidden=true;
 try{if(!worker){worker=new Worker('worker.js');worker.onmessage=({data})=>{if(!busy||data.id!==busy.id)return;if(data.type==='status'){$('run-status').textContent=data.message;return;}const current=busy;finish(data.results||[],data.output||'',current,data.type==='error'?data.error:null);};worker.onerror=()=>{stop('Python worker could not load. Check your connection and try again.');};}
 timer=setTimeout(()=>stop('Run timed out after 120 seconds. Check for an infinite loop or retry after the runtime has downloaded.'),120000);worker.postMessage({id:job.id,code,tests:check?lesson.tests:[],packages:lesson.packages});
 }catch(e){stop('Python runtime unavailable: '+e.message);}
}
$('editor').addEventListener('input',()=>{const r=record();r.code=$('editor').value;r.passed=false;r.checkedCode='';$('run-status').textContent='Code changed. Check this version again.';save();counters();});
$('guided-editor').oninput=()=>{record().guidedCode=$('guided-editor').value;save();};$('guided-run').onclick=()=>run(false,true);
$('reflection').oninput=()=>{record().reflection=$('reflection').value;save();};$('run').onclick=()=>run(false);$('check').onclick=()=>run(true);$('stop').onclick=()=>stop();
$('reset').onclick=()=>{stop();const r=record();r.code=lesson.starter;r.passed=false;r.checkedCode='';$('editor').value=r.code;$('results').replaceChildren();$('output').textContent='';save();counters();};
$('hint').onclick=()=>{const r=record();r.hints=Math.min(r.hints+1,3);$('hint-text').textContent=lesson.hints[r.hints-1];$('hint').textContent=r.hints===3?'All 3 hints opened':`Need a hint? (${r.hints}/3)`;save();};
$('reference-toggle').onclick=()=>{const opening=$('reference').hidden;$('reference').hidden=!opening;$('reference-toggle').setAttribute('aria-expanded',String(opening));if(opening){record().reference=true;save();}};
$('project-link').oninput=()=>{project().link=$('project-link').value;project().reviewed=false;save();counters();};$('project-reflection').oninput=()=>{project().reflection=$('project-reflection').value;project().reviewed=false;save();counters();};
$('review-project').onclick=()=>{const p=project();if(!p.checks.every(Boolean)||p.reflection.trim().length<30){$('project-status').textContent='Check all three requirements and write at least 30 characters about your work.';return;}if(p.link&&!safeURL(p.link)){$('project-status').textContent='Use a valid HTTPS link or leave it blank.';return;}p.link=safeURL(p.link);p.reviewed=true;save();counters();$('project-status').textContent='Self-review saved. This does not mean a teacher has verified the project.';};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-code').onclick=()=>download($('editor').value,lesson.id+(lesson.language==='html'?'.html':'.py'),'text/plain');$('export').onclick=()=>download(JSON.stringify(state,null,2),'python-internship-progress.json','application/json');
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>3000000)throw Error('Backup is too large.');const next=cleanState(JSON.parse(await f.text()));stop();state=next;openLesson(state.current);$('save-status').textContent=storageOK?'Backup imported and saved on this device.':'Backup imported for this session. Export to keep it.';}catch(error){$('save-status').textContent='Import failed: '+error.message;}e.target.value='';};
$('resume').onclick=()=>{const next=C.lessons.find(l=>l.level!=='stretch'&&!state.lessons[l.id]?.passed)||C.lessons[0];openLesson(next.id);$('week-title').scrollIntoView?.({behavior:'smooth',block:'start'});};$('menu').onclick=()=>{const open=$('weeks').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open));};
$('start-zero').onclick=()=>openLesson(C.lessons[0].id);$('lesson-select').onchange=e=>openLesson(e.target.value);
function nextLesson(direction){const route=C.lessons.filter(l=>l.level!=='stretch');const i=route.findIndex(l=>l.id===lesson.id);const target=route[Math.max(0,Math.min(route.length-1,i+direction))];openLesson(target.id);$('lesson-title').scrollIntoView?.({behavior:'smooth',block:'start'});}
$('previous-lesson').onclick=()=>nextLesson(-1);$('next-lesson').onclick=()=>nextLesson(1);
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(validIds.has(id)&&id!==lesson.id)openLesson(id);});
openLesson(validIds.has(location.hash.slice(1))?location.hash.slice(1):state.current);
})();
