/* Teaching aids, notebook exchange and editor support. All imported code remains inert. */
(()=>{'use strict';const $=id=>document.getElementById(id);let current;
function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderVideos(){const list=$('video-list');list.replaceChildren();const videos=(current.videos||[]).filter(v=>$('video-language').value==='all'||v.language===$('video-language').value);if(!videos.length){const p=document.createElement('p');p.className='small';p.textContent='No topic-matched video in this language is selected yet. Try English + Hindi and use the written walkthrough.';list.append(p);return;}videos.forEach((v,i)=>{const card=document.createElement('article');card.className='video-card';const badge=document.createElement('small');badge.textContent=(v.recommended?'Start here · ':'Optional · ')+v.language;const a=document.createElement('a');a.href=v.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=v.title+' ↗';const creator=document.createElement('span');creator.textContent=v.creator;const focus=document.createElement('p');focus.textContent=v.focus;card.append(badge,a,creator,focus);list.append(card);});}
function changed(el){el.dispatchEvent(new Event('input',{bubbles:true}));position(el);}
function position(el){if(el.id!=='editor')return;const before=el.value.slice(0,el.selectionStart),lines=before.split('\n');$('cursor-position').textContent=`Line ${lines.length} · Column ${lines.at(-1).length+1}`;}
function indent(el,remove=false){const value=el.value,a=el.selectionStart,b=el.selectionEnd,start=value.lastIndexOf('\n',a-1)+1;let end=value.indexOf('\n',b);if(end<0)end=value.length;const block=value.slice(start,end);const adjusted=block.split('\n').map(line=>remove?line.replace(/^( {1,4}|\t)/,''):'    '+line).join('\n');el.setRangeText(adjusted,start,end,'select');changed(el);el.focus();}
function setupEditor(el){el.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();if(e.shiftKey||el.selectionStart!==el.selectionEnd)indent(el,e.shiftKey);else{const spaces=4-(el.selectionStart-(el.value.lastIndexOf('\n',el.selectionStart-1)+1))%4;el.setRangeText(' '.repeat(spaces),el.selectionStart,el.selectionEnd,'end');changed(el)}}else if(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&current?.language==='python'){e.preventDefault();const line=el.value.slice(0,el.selectionStart).split('\n').at(-1);const leading=line.match(/^[ \t]*/)[0].replace(/\t/g,'    ');const extra=/^(?:async\s+)?(?:def|class|if|elif|else|for|while|try|except|finally|with|match|case)\b.*:\s*(?:#.*)?$/.test(line.trim())?'    ':'';el.setRangeText('\n'+leading+extra,el.selectionStart,el.selectionEnd,'end');changed(el)}});['click','keyup','input'].forEach(event=>el.addEventListener(event,()=>position(el)));}
setupEditor($('editor'));setupEditor($('guided-editor'));
$('indent').onclick=()=>indent($('editor'));$('outdent').onclick=()=>indent($('editor'),true);$('spaces').onclick=()=>{const el=$('editor');el.value=el.value.replace(/^[ \t]+/gm,leading=>{let column=0;return Array.from(leading,c=>{const n=c==='\t'?4-column%4:1;column+=n;return ' '.repeat(n)}).join('')});changed(el);el.focus();};
$('video-language').onchange=renderVideos;
$('open-notebook').onclick=()=>{$('notebook-host').hidden=false;$('notebook-frame').src=$('notebook-tab').href;$('notebook-status').textContent='Opening JupyterLite. Its files save separately from course progress.';};
$('close-notebook').onclick=()=>{$('notebook-host').hidden=true;$('notebook-frame').removeAttribute('src');};
$('notebook-draft').onclick=()=>{const n={nbformat:4,nbformat_minor:5,metadata:{internship_lesson:current.id,kernelspec:{name:'python',display_name:'Python (Pyodide)',language:'python'}},cells:[{id:'instructions',cell_type:'markdown',metadata:{},source:[current.title+'\n\n'+current.goal+'\n\nRun with Shift+Enter. Download, then import this notebook in the same course lesson to check your answer.']},{id:'answer',cell_type:'code',metadata:{internship_role:'student'},execution_count:null,outputs:[],source:[$('editor').value]}]};download(JSON.stringify(n,null,2),current.id+'-my-answer.ipynb');};
function readAnswer(n,id){if(!n||n.nbformat!==4||!Array.isArray(n.cells)||n.metadata?.internship_lesson!==id)throw Error('Use a course notebook for this same lesson. Its lesson ID must match.');let parts=[];for(const c of n.cells){if(c.cell_type!=='code')continue;const role=c.metadata?.internship_role;if(role&&role!=='student')continue;const src=typeof c.source==='string'?c.source:Array.isArray(c.source)&&c.source.every(s=>typeof s==='string')?c.source.join(''):null;if(src===null)throw Error('A code cell has an invalid source.');parts.push(src);}const code=parts.join('\n\n');if(!parts.length||code.length>50000)throw Error('No answer cells found, or the answer is too large.');return code;}
$('notebook-import').onchange=async e=>{const file=e.target.files[0];if(!file)return;const id=current.id;try{if(file.size>1000000)throw Error('Notebook exceeds 1 MB. Clear outputs in Jupyter and download again.');const n=JSON.parse(await file.text());if(current.id!==id)throw Error('Lesson changed during import. Choose the file again.');const code=readAnswer(n,id);$('editor').value=code;changed($('editor'));$('notebook-status').textContent='Answer imported into the editor. Review it, then click Check my code. Nothing has run yet.';}catch(error){$('notebook-status').textContent='Import failed: '+error.message;}e.target.value='';};
window.CourseLearning={readAnswer,render(lesson,record){current=lesson;$('lesson-count').textContent=window.INTERNSHIP_COURSE.lessons.length;$('walkthrough-section').hidden=!lesson.walkthrough;const list=$('walkthrough');list.replaceChildren();for(const line of lesson.walkthrough||[]){const li=document.createElement('li');li.textContent=line;list.append(li);}$('expected-output').textContent=lesson.expectedOutput||'';$('mistake-card').hidden=!lesson.commonMistake;$('common-mistake').textContent=lesson.commonMistake||'';$('guided-lab').hidden=!lesson.guided;$('guided-prompt').textContent=lesson.guided?.prompt||'';$('guided-editor').value=record.guidedCode??lesson.guided?.starter??'';$('guided-output').textContent='';$('prerequisite').hidden=!lesson.prerequisite;$('prerequisite').textContent=lesson.prerequisite||'';$('error-help').hidden=true;renderVideos();$('notebook-section').hidden=lesson.language!=='python';$('notebook-host').hidden=true;$('notebook-frame').removeAttribute('src');$('notebook-tab').href='notebooks/lab/index.html?path='+encodeURIComponent(lesson.id+'.ipynb');$('notebook-starter').href='notebook-content/'+lesson.id+'.ipynb';$('notebook-status').textContent='';position($('editor'));},errorHelp(error){const text=String(error);let help='';if(/IndentationError|TabError/.test(text))help='Spacing help: check the highlighted line and the line above it. A line ending in : starts a block. Use four spaces inside that block and align sibling statements. Select lines and use Indent/Outdent; convert leading tabs if needed.';else if(/SyntaxError/.test(text))help='Syntax help: check matching quotes and brackets, then a missing colon after if, for or def. Read the line just above the reported error too.';else if(/NameError/.test(text))help='Name help: check spelling and capitalization. Define the variable before using it. In Jupyter, run earlier cells or restart and run all cells in order.';else if(/TypeError/.test(text))help='Type help: inspect type(value). Text and numbers need different operations; convert numeric input before calculating.';$('error-help').textContent=help;$('error-help').hidden=!help;}};
})();
