const fs=require('fs'),path=require('path'),assert=require('assert'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const files=['curriculum.js','learning-ui.js','app.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8'));const jobs=[];
function boot(saved){const dom=new JSDOM(html,{url:'https://study.example/internship/',runScripts:'outside-only'});const w=dom.window;w.Worker=class{postMessage(data){jobs.push({worker:this,data})}terminate(){this.terminated=true}};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};if(saved)w.localStorage.setItem('ljiet_python_internship_v1',saved);files.forEach(f=>w.eval(f));return w;}
let w=boot(),d=w.document,$=id=>d.getElementById(id),key='ljiet_python_internship_v1';
function answer(text){$('editor').value=text;$('editor').dispatchEvent(new w.Event('input'));}
function finish(pass=true){const job=jobs.at(-1);job.worker.onmessage({data:{id:job.data.id,type:'done',output:'',results:job.data.tests.map(t=>({label:t.label,pass}))}});return job;}
assert.equal(w.INTERNSHIP_COURSE.lessons.length,112);assert.equal(d.querySelectorAll('#week-list button').length,16);assert.equal($('lesson-title').textContent,'Your first line of Python');assert.ok(!$('editor').value.includes('def '));assert.equal($('reference').hidden,true);assert.equal(d.querySelectorAll('#lesson-tabs button').length,8);assert.equal(d.querySelectorAll('#stretch-tabs button').length,3);assert.equal($('stretch-group').open,false);
assert.ok(d.querySelector('#video-list a').href.includes('youtube.com/watch?v='));$('video-language').value='Hindi';$('video-language').dispatchEvent(new w.Event('change'));assert.match($('video-list').textContent,/CodeWithHarry/);
// Worked-example runs must not award completion or overwrite the independent draft.
$('guided-editor').value='print("guided")';$('guided-editor').dispatchEvent(new w.Event('input'));$('guided-run').click();assert.equal(jobs.at(-1).data.code,'print("guided")');finish();assert.equal($('independent').textContent,'0');assert.ok($('editor').value.includes('#'));
answer('print("I am learning Python")');$('check').click();assert.equal(jobs.at(-1).data.code,$('editor').value);assert.equal(jobs.at(-1).data.tests[0].outputEquals,'I am learning Python');finish();assert.equal($('independent').textContent,'1');
answer($('editor').value+'\n# edited');assert.equal($('independent').textContent,'0');$('hint').click();$('check').click();finish();assert.equal($('assisted').textContent,'1');$('check').click();finish(false);assert.equal($('assisted').textContent,'0');
// Results for an older version cannot pass a newer draft.
$('check').click();answer($('editor').value+'\n# newer');finish();assert.equal($('assisted').textContent,'0');assert.match($('run-status').textContent,/changed/);
$('check').click();const late=jobs.at(-1);$('next-lesson').click();assert.equal(late.worker.terminated,true);late.worker.onmessage({data:{id:late.data.id,type:'done',results:[{pass:true}]}});assert.equal($('independent').textContent,'0');assert.equal($('lesson-title').textContent,'Read code from top to bottom');
// Real keyboard helpers: block indent, multi-line outdent, tabs and line position.
answer('if True:');$('editor').setSelectionRange(8,8);$('editor').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.equal($('editor').value,'if True:\n    ');answer('x=1\ny=2');$('editor').select();$('indent').click();assert.equal($('editor').value,'    x=1\n    y=2');$('outdent').click();assert.equal($('editor').value,'x=1\ny=2');answer('\tprint("x")');$('spaces').click();assert.equal($('editor').value,'    print("x")');w.CourseLearning.errorHelp('IndentationError: expected an indented block');assert.equal($('error-help').hidden,false);assert.match($('error-help').textContent,/four spaces/);
// Notebook route is in-app and lesson-specific; loading is explicit.
assert.equal($('notebook-frame').hasAttribute('src'),false);$('open-notebook').click();assert.ok($('notebook-frame').src.includes('/notebooks/lab/index.html?path=f01-l2.ipynb'));$('close-notebook').click();assert.equal($('notebook-frame').hasAttribute('src'),false);
const notebook={nbformat:4,metadata:{internship_lesson:'f01-l2'},cells:[{cell_type:'code',metadata:{internship_role:'example'},source:['print("example")']},{cell_type:'code',metadata:{internship_role:'student'},source:['print("Ready")\n','print("Go")']},{cell_type:'code',metadata:{internship_role:'tests'},source:['assert False']}]};assert.equal(w.CourseLearning.readAnswer(notebook,'f01-l2'),'print("Ready")\nprint("Go")');assert.throws(()=>w.CourseLearning.readAnswer(notebook,'f01-l1'),/same lesson/);assert.throws(()=>w.CourseLearning.readAnswer({...notebook,cells:[{cell_type:'code',source:[123]}]},'f01-l2'),/invalid source/);
// Every route has resources; all core lessons are reachable, optional work is explicit.
for(let n=1;n<=16;n++){d.querySelectorAll('#week-list button')[n-1].click();assert.ok(d.querySelectorAll('#lesson-tabs button').length>=4);assert.ok(fs.existsSync(path.join(root,$('project-download').getAttribute('href'))));if(n!==9)assert.ok(fs.existsSync(path.join(root,$('notebook-starter').getAttribute('href'))));}
// Project evidence requires all requirements and an explanation; invalid URLs are refused.
$('review-project').click();assert.equal($('reviewed').textContent,'0');d.querySelectorAll('#project-checklist input').forEach(x=>{x.checked=true;x.dispatchEvent(new w.Event('change'))});$('project-reflection').value='I added a validation case and fixed a missing boundary check before running the route tests.';$('project-reflection').dispatchEvent(new w.Event('input'));$('project-link').value='javascript:alert(1)';$('project-link').dispatchEvent(new w.Event('input'));$('review-project').click();assert.equal($('reviewed').textContent,'0');$('project-link').value='https://github.com/student/project';$('project-link').dispatchEvent(new w.Event('input'));$('review-project').click();assert.equal($('reviewed').textContent,'1');
const saved=w.localStorage.getItem(key);w.close();w=boot(saved);d=w.document;$=id=>d.getElementById(id);assert.equal($('reviewed').textContent,'1');$('start-zero').click();assert.equal($('lesson-title').textContent,'Your first line of Python');assert.equal($('guided-editor').value,'print("guided")');
// A simple HTML page keeps its isolated preview.
d.querySelectorAll('#week-list button')[8].click();answer(w.INTERNSHIP_COURSE.lessons.find(l=>l.id==='f09-l1').reference);$('check').click();assert.equal($('preview').getAttribute('sandbox'),'allow-scripts');assert.equal(d.querySelectorAll('#results .pass').length,2);assert.equal($('notebook-section').hidden,true);
w.close();w=boot('{broken');assert.ok(w.document.getElementById('editor').value);w.close();
console.log('PASS: beginner-first flow, all weeks, videos/language filtering, guided versus independent runs, stale results, backups, indentation helpers, notebook exchange/routes, projects and isolated HTML');
