const fs=require('fs'),path=require('path'),assert=require('assert'),{JSDOM}=require('jsdom');
const pages=['index.html','python/index.html','maths/index.html','probability/index.html','probability/chapter-4.html','study/index.html','internship/index.html','loops-adventure.html'];
const script=fs.readFileSync('js/theme-switcher.js','utf8');
for(const page of pages){for(const saved of ['light','dark',null]){const dom=new JSDOM(fs.readFileSync(page,'utf8'),{url:'https://hub.test/'+page,runScripts:'outside-only'}),w=dom.window;w.matchMedia=()=>({matches:true,addEventListener(){}});if(saved)w.localStorage.setItem('ljiet_theme',saved);w.eval(script);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));assert.equal(w.document.documentElement.dataset.theme,saved||'dark');assert.equal(w.document.body.dataset.theme,saved||'dark');const button=w.document.getElementById('themeToggleBtn');assert(button,page+' lacks toggle');const current=w.document.documentElement.dataset.theme;w.toggleTheme();assert.equal(w.document.documentElement.dataset.theme,current==='dark'?'light':'dark');assert.equal(w.localStorage.getItem('ljiet_theme'),w.document.documentElement.dataset.theme);assert.equal(button.getAttribute('aria-pressed'),String(w.document.documentElement.dataset.theme==='dark'));w.dispatchEvent(new w.StorageEvent('storage',{key:'ljiet_theme',newValue:'light'}));assert.equal(w.document.documentElement.dataset.theme,'light');assert.equal(w.document.querySelectorAll('script[src$="theme-switcher.js"]').length,1);for(const stylesheet of ['design-system.css','theme-surfaces.css'])assert(w.document.querySelector(`link[href$="${stylesheet}"]`));dom.window.close();}}
const css=fs.readFileSync('css/design-system.css','utf8')+fs.readFileSync('css/theme-surfaces.css','utf8');assert.equal((css.match(/{/g)||[]).length,(css.match(/}/g)||[]).length);
function luminance(hex){return hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0)}
function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
for(const [label,fg,bg] of [['light text','#191a32','#ffffff'],['light secondary','#62627b','#ffffff'],['dark text','#f5f3ff','#1c1d30'],['dark secondary','#b4b1ca','#1c1d30'],['light action','#ffffff','#4947cf'],['dark action','#171526','#aaa5ff'],['light code','#23334a','#edf1f8'],['dark code','#e5edff','#111727'],['paper','#171717','#ffffff']])assert(contrast(fg,bg)>=4.5,label+' contrast '+contrast(fg,bg));
const sw=fs.readFileSync('service-worker.js','utf8');assert(sw.includes('./css/theme-surfaces.css'));console.log('PASS: 8 page theme bootstraps, system/default and saved preferences, toggles, cross-tab updates, accessible state, core palette contrast and offline asset.');
